version: '3.9'

services:
  asesmen-paud:
    image: ${DOCKER_IMAGE}
    container_name: asesmen-paud
    build:
      context: .
      target: build
    ports:
      - ${PORT}:${PORT}
      - 3333:3333
      - 9229:9229
    env_file:
      - .env
    volumes:
      - /home/node/app/node_modules
      - storage_data:/home/node/app/storage
    command: >
      sh -c '
        # Check if .env exists
        if [ ! -f .env ]; then
          echo "Error: .env file not found!"
          exit 1
        fi

        # Check if APP_KEY exists in .env
        if ! grep -q "APP_KEY=" .env; then
          echo "Error: APP_KEY not set in .env!"
          exit 1
        fi

        # Run using pnpm
        exec pnpm start
      '
    depends_on:
      - asesmen-paud-postgresql

  asesmen-paud-postgresql:
    image: postgres:17
    container_name: asesmen-paud-postgresql
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  storage_data:
